travis:
  secure:
    BINSTAR_TOKEN: TpeqQDAjVmiakDhNdLAbNg6eSSfm22zjxls8pAvl+WYL0BxlMbHYURFcoo20ZYWvlvkGBZNHkoP7flUmL+f/VMzsrDWleHI+wIjRsgMiiAJbvHUfAt/wHNJfNxUssUXz3jJIyg2E7eT389nT5V3nc2+a56FowGzgjCp7BDC2qJ8nSKX787XhDSY2tGq/UlDGxExYZA45I+WQ1AC2PIUFDgPW+bi5cRA3EoL+waCAGhKxhZZ9S1q6KtgluNlbDn24E6DYwn6FWKIZBX3BA7XAnwoXcCKymVsPwEFg1ZY0mHAy26zzz7ato/Lt3+IWY1TdRwVuVqpNOdAoyfqUBL0TuC0ZHHrdko32RClfjjgwJG+wId+UKIM5fQCsKdNpXJjG8PqIy3kVY3Gs5DGSZ1blhlWQcm5aaDb+O/lv95n7Ff/8y1PvoTvHLnsgH0ATl+GdMUQUX+qrmdGQAdHl4ce5yt4z5o83Q5hs9g7A/GSih2n3zW2EOSbOwdzr7Xe3P14loJSTNNz64vXXODr/AOZwVMIKLP2TXYXjiU1DiNWBsU/IwWn45dgq6kOMkbuYvZXb2jLlUTCQF14iiweG49eiI7BUKOOtaiPVLi810WpuhSHmVheWLjj9x2Gh9eVFpO7yJIo/sSEjPU+MiFjQdY9yUiUeXLX+sbHkMcf19wXO/Y8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
